on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
name: 🚀 Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build && npm run build tailwind-build-ci
    
    - name: 📂 Sync files (quezada.nl)
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.hypnoticsiege.net
        username: hypnoti1
        password: ${{ secrets.password }}
        server-dir: /domains/quezada.nl/public_html/
        local-dir: ./dist/
        
    - name: 📂 Sync files (hypnoticsiege.net)
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.hypnoticsiege.net
        username: hypnoti1
        password: ${{ secrets.password }}
        server-dir: /domains/hypnoticsiege.net/public_html/
        local-dir: ./dist/
